param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
)

$ErrorActionPreference = "Stop"

$moduleRules = @(
    @{ Pattern = "TestCalcMatrix"; Module = "Matrix"; Prefix = "UT_MTX"; Target = "Matrix transform math" },
    @{ Pattern = "TestVertexHelperUtils"; Module = "Mesh"; Prefix = "UT_MESH"; Target = "VertexHelperUtils" },
    @{ Pattern = "TestUIMeshData|TestUIMeshDataX|TestMeshSlim"; Module = "Mesh"; Prefix = "UT_MESH"; Target = "UIMeshData" },
    @{ Pattern = "TestGeometryBuffer|TestUIGeometry"; Module = "Geometry"; Prefix = "UT_GEO"; Target = "UIGeometry" },
    @{ Pattern = "TestFreeListAllocator|TestSharedArray|TestUnsafeFastCopy|TestManagedTaskCoverage"; Module = "Utility"; Prefix = "UT_UTIL"; Target = "Low-level utility" },
    @{ Pattern = "TestResourceUtility"; Module = "Utility"; Prefix = "UT_UTIL"; Target = "ResourceUtility" },
    @{ Pattern = "TestTextureSlotTable"; Module = "Texture"; Prefix = "UT_TEX"; Target = "TextureSlotTable" },
    @{ Pattern = "TestMergeBatcher|TestHolderBatchRenderer"; Module = "Batching"; Prefix = "UT_BATCH"; Target = "MergeBatcher" },
    @{ Pattern = "TestHolderLifecycle|TestHolderNotifier|TestUIPrefabRegistration|TestOwnerRegistry|TestUIPrefabHolderCoverage|TestPrefabHolderExtCoverage"; Module = "Prefab"; Prefix = "UT_PREF"; Target = "UIPrefab lifecycle" },
    @{ Pattern = "TestMaterialBinder"; Module = "Material"; Prefix = "UT_MAT"; Target = "MaterialBinder" },
    @{ Pattern = "TestUIText|TestUIImage|TestUIOutline"; Module = "UI"; Prefix = "UT_UI"; Target = "UI draw target" },
    @{ Pattern = "TestPerfProbe|TestLogHygiene"; Module = "Diagnostics"; Prefix = "UT_DIAG"; Target = "PerfProbe diagnostics" },
    @{ Pattern = "TestManagedCodeInJob|TestMergeJobs|TestBurstMergeJobs|TestMeshJobsCoverage"; Module = "Jobs"; Prefix = "UT_JOB"; Target = "Merge jobs" },
    @{ Pattern = "TestPerfBaselineRunner|TestEightSlotPerfRunner|TestDynamicSwapRunner"; Module = "Performance"; Prefix = "UT_PERF"; Target = "Scene perf runners" },
    @{ Pattern = "TestOverCapacityScene|TestPerfProbeCsvScene|TestThreeSlotScene|TestUseSlimLifecycle"; Module = "Scenes"; Prefix = "UT_SCENE"; Target = "Scene integration" }
)

function Get-RelativePath([string]$Path) {
    $root = (Resolve-Path $ProjectRoot).Path.TrimEnd('\')
    $full = (Resolve-Path $Path).Path
    return $full.Substring($root.Length + 1).Replace('\', '/')
}

function Get-ModuleInfo([string]$FileName) {
    foreach ($rule in $moduleRules) {
        if ($FileName -match $rule.Pattern) {
            return [pscustomobject]$rule
        }
    }

    return [pscustomobject]@{
        Pattern = "*"
        Module = "Misc"
        Prefix = "UT_MISC"
        Target = "Misc Unity tests"
    }
}

function Convert-Summary([string]$MethodName) {
    return ($MethodName -replace "_", " ").Trim()
}

function New-TestRecordText($test) {
    $frontmatter = New-TestRecordFrontmatter $test
    $body = @(
        "",
        "# $($test.Id)",
        "",
        "## Requirement",
        "$($test.Summary).",
        "",
        "## Risk",
        "Regression in $($test.Target) could break the documented Unity UIDataRender behavior.",
        "",
        "## Steps",
        "1. Run the $($test.TestType) test assembly containing ``$($test.Method)``.",
        "2. Let the NUnit/Unity Test Runner execute the assertions.",
        "",
        "## Assertions",
        "See ``$($test.File)`` / ``$($test.Method)``.",
        "",
        "## Expected Result",
        "The test passes without unexpected logs, leaks, or assertion failures.",
        "",
        "## Latest Run Result",
        "Unknown until the next Unity Test Runner execution.",
        "",
        "## Notes",
        "Generated by ``Tools/UnityTestRunner/Sync-UnitTestGovernance.ps1``."
    )
    return ($frontmatter + $body -join [Environment]::NewLine) + [Environment]::NewLine
}

function New-TestRecordFrontmatter($test) {
    return @(
        "---",
        "testId: $($test.Id)",
        "module: $($test.Module)",
        "testType: $($test.TestType)",
        "target: $($test.Target)",
        "testFile: $($test.File)",
        "testMethod: $($test.Method)",
        "status: active",
        "lastRun: `"`"",
        "lastResult: unknown",
        "---"
    )
}

function Update-TestRecordText([string]$Path, $test) {
    if (-not (Test-Path -LiteralPath $Path)) {
        Set-Content -LiteralPath $Path -Value (New-TestRecordText $test) -Encoding UTF8
        return
    }

    $existing = Get-Content -LiteralPath $Path -Raw
    $frontmatter = (New-TestRecordFrontmatter $test) -join [Environment]::NewLine
    if ($existing -match '(?s)^---\r?\n.*?\r?\n---') {
        $updated = [regex]::Replace($existing, '(?s)^---\r?\n.*?\r?\n---', $frontmatter, 1)
        Set-Content -LiteralPath $Path -Value $updated -Encoding UTF8
        return
    }

    Set-Content -LiteralPath $Path -Value (($frontmatter + [Environment]::NewLine + [Environment]::NewLine + $existing)) -Encoding UTF8
}

function Read-TextLines([string]$Path) {
    $list = [System.Collections.ArrayList]::new()
    [void]$list.AddRange([string[]](Get-Content -LiteralPath $Path))
    Write-Output -NoEnumerate $list
}

function Write-TextLines([string]$Path, [System.Collections.IEnumerable]$Lines) {
    Set-Content -LiteralPath $Path -Value $Lines -Encoding UTF8
}

$testRoot = Join-Path $ProjectRoot "Assets\Tests"
if (-not (Test-Path $testRoot)) {
    throw "Test root not found: $testRoot"
}

$tests = New-Object System.Collections.Generic.List[object]
$testFiles = & rg --files (Join-Path $ProjectRoot "Assets\Tests") -g "*.cs"
if ($LASTEXITCODE -ne 0) {
    throw "Failed to enumerate test files with rg."
}

$files = $testFiles |
    ForEach-Object {
        if ([System.IO.Path]::IsPathRooted($_)) {
            [System.IO.FileInfo]$_
        } else {
            [System.IO.FileInfo](Join-Path $ProjectRoot $_)
        }
    } |
    Sort-Object FullName

foreach ($file in $files) {
    $relative = Get-RelativePath $file.FullName
    $module = Get-ModuleInfo $file.Name
    $lines = Get-Content -LiteralPath $file.FullName
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -notmatch '^\s*\[(Test|UnityTest)\]') {
            continue
        }

        $attrIndex = $i
        $testAttr = $matches[1]
        $methodIndex = -1
        $methodName = $null
        for ($j = $i + 1; $j -lt [Math]::Min($i + 10, $lines.Count); $j++) {
            if ($lines[$j] -match '\b(public|private|internal)\s+(?:unsafe\s+)?(?:IEnumerator|void)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(') {
                $methodIndex = $j
                $methodName = $matches[2]
                break
            }
        }

        if ($methodIndex -lt 0) {
            continue
        }

        $existingId = $null
        for ($k = [Math]::Max(0, $attrIndex - 4); $k -le [Math]::Min($methodIndex, $lines.Count - 1); $k++) {
            if ($lines[$k] -match 'UT_[A-Z]+_\d{3}') {
                $existingId = $matches[0]
                break
            }
        }

        $tests.Add([pscustomobject]@{
            Id = $existingId
            Prefix = $module.Prefix
            Module = $module.Module
            Target = $module.Target
            File = $relative
            FullPath = $file.FullName
            Method = $methodName
            AttrIndex = $attrIndex
            MethodIndex = $methodIndex
            TestType = if ($relative -match '/PlayMode/') { "PlayMode" } else { "EditMode" }
            TestAttribute = $testAttr
            Summary = Convert-Summary $methodName
        })
    }
}

$usedNumbers = @{}
foreach ($test in $tests) {
    if (-not $usedNumbers.ContainsKey($test.Prefix)) {
        $usedNumbers[$test.Prefix] = New-Object System.Collections.Generic.HashSet[int]
    }
    if ($test.Id -match '^(.+)_([0-9]{3})$') {
        [void]$usedNumbers[$test.Prefix].Add([int]$matches[2])
    }
}

$nextNumber = @{}
foreach ($prefix in ($tests | Select-Object -ExpandProperty Prefix -Unique)) {
    $nextNumber[$prefix] = 1
}

foreach ($test in ($tests | Sort-Object Prefix, File, AttrIndex)) {
    if ($test.Id) {
        continue
    }

    while ($usedNumbers[$test.Prefix].Contains($nextNumber[$test.Prefix])) {
        $nextNumber[$test.Prefix]++
    }
    $id = "{0}_{1:D3}" -f $test.Prefix, $nextNumber[$test.Prefix]
    $test.Id = $id
    [void]$usedNumbers[$test.Prefix].Add($nextNumber[$test.Prefix])
    $nextNumber[$test.Prefix]++
}

foreach ($group in ($tests | Group-Object FullPath)) {
    $path = $group.Name
    $lines = Read-TextLines $path

    foreach ($test in ($group.Group | Sort-Object AttrIndex -Descending)) {
        $attrIndex = $test.AttrIndex
        $methodIndex = $test.MethodIndex
        $indent = ""
        if ($lines[$attrIndex] -match '^(\s*)') {
            $indent = $matches[1]
        }

        $recordPath = "Documentation~/Testing/Unit/$($test.Module)/$($test.Id).md"
        $hasRecord = $false
        for ($i = [Math]::Max(0, $attrIndex - 4); $i -lt $attrIndex; $i++) {
            if ($lines[$i] -match 'TestRecord:') {
                $hasRecord = $true
                break
            }
        }

        $hasCategory = $false
        for ($i = $attrIndex; $i -le [Math]::Min($methodIndex, $lines.Count - 1); $i++) {
            if ($lines[$i] -match '\[Category\("UT_[A-Z]+_\d{3}"\)\]') {
                $hasCategory = $true
                break
            }
        }

        if (-not $hasCategory) {
            $lines.Insert($attrIndex + 1, "$indent[Category(`"$($test.Id)`")]")
        }
        if (-not $hasRecord) {
            $lines.Insert($attrIndex, "$indent// TestRecord: $recordPath")
        }
    }

    Write-TextLines $path $lines
}

$docRoot = Join-Path $ProjectRoot "Documentation~\Testing\Unit"
New-Item -ItemType Directory -Force -Path $docRoot | Out-Null

foreach ($test in $tests) {
    $moduleDir = Join-Path $docRoot $test.Module
    New-Item -ItemType Directory -Force -Path $moduleDir | Out-Null
    $recordPath = Join-Path $moduleDir "$($test.Id).md"
    Update-TestRecordText -Path $recordPath -test $test
}

$readme = New-Object System.Collections.Generic.List[string]
$readme.Add("# Unity Unit Test Governance")
$readme.Add("")
$readme.Add("Generated by ``Tools/UnityTestRunner/Sync-UnitTestGovernance.ps1``.")
$readme.Add("")
$readme.Add("## TestId Prefixes")
$readme.Add("")
$readme.Add("| Module | Prefix | Range | In use | Target |")
$readme.Add("|---|---|---:|---:|---|")
foreach ($module in ($tests | Group-Object Module | Sort-Object Name)) {
    $first = $module.Group | Select-Object -First 1
    $count = $module.Group.Count
    $max = ($module.Group | ForEach-Object { if ($_.Id -match '_(\d{3})$') { [int]$matches[1] } } | Measure-Object -Maximum).Maximum
    $maxText = [string]::Format("{0:D3}", [int][Math]::Max($max, 1))
    $readme.Add("| $($first.Module) | ``$($first.Prefix)`` | 001-$maxText | $count | $($first.Target) |")
}
$readme.Add("")
$readme.Add("## Active Tests")
$readme.Add("")
$readme.Add("| TestId | Module | Type | Test | Record |")
$readme.Add("|---|---|---|---|---|")
foreach ($test in ($tests | Sort-Object Id)) {
    $record = "Documentation~/Testing/Unit/$($test.Module)/$($test.Id).md"
    $readme.Add("| ``$($test.Id)`` | $($test.Module) | $($test.TestType) | ``$($test.Method)`` | [$($test.Id)]($($test.Module)/$($test.Id).md) |")
}
$readme.Add("")
$readme.Add("## Tombstoned ids")
$readme.Add("")
$readme.Add("None.")
Set-Content -LiteralPath (Join-Path $docRoot "README.md") -Value $readme -Encoding UTF8

Write-Host "Synchronized $($tests.Count) Unity test records."
